/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPrincipal.java
 *
 * Created on May 25, 2010, 10:28:51 PM
 */
package com.gazoomobile.mfw.client;

import com.gazoomobile.mfw.platform.client.Application;
import com.gazoomobile.mfw.platform.client.ControlProperty;
import com.gazoomobile.mfw.platform.client.Screen;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yunisel
 */
public class JPrincipal extends javax.swing.JFrame {
//    private int posX=0;
//    private int posY=0;
//    private Aplicacion App;
//    private int pantallaActual;
//    private int componenteActual;
//    private boolean vLayaout = false;
//    private boolean hLayaout = false;

    private Application application;
    private Screen actualScreen;
    private JPanel activePanel;
    private String activeComponent;

    public JPrincipal() {
        initComponents();
//        App = new Aplicacion();
//        pantallaActual=0;
//        componenteActual=0;
        main_panel.setLayout(new BoxLayout(main_panel, BoxLayout.PAGE_AXIS));
        activePanel = main_panel;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ButtonButton = new javax.swing.JButton();
        ListButton = new javax.swing.JButton();
        ComboButton = new javax.swing.JButton();
        HLayoutButton = new javax.swing.JButton();
        TextBoxButton = new javax.swing.JButton();
        CheckButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        VLayoutButton = new javax.swing.JButton();
        LabelButton = new javax.swing.JButton();
        TableButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        main_panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setAlignmentX(50.0F);
        jPanel4.setAlignmentY(50.0F);
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        ButtonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazoomobile/mfw/client/images/boton.png"))); // NOI18N
        ButtonButton.setText("Button");
        ButtonButton.setAlignmentY(0.0F);
        ButtonButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtonButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ButtonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonButtonActionPerformed(evt);
            }
        });

        ListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazoomobile/mfw/client/images/list.png"))); // NOI18N
        ListButton.setText("ListBox");
        ListButton.setAlignmentY(0.0F);
        ListButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ListButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListButtonActionPerformed(evt);
            }
        });

        ComboButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazoomobile/mfw/client/images/combo.png"))); // NOI18N
        ComboButton.setText("ComboBox");
        ComboButton.setAlignmentY(0.0F);
        ComboButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ComboButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ComboButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ComboButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboButtonActionPerformed(evt);
            }
        });

        HLayoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazoomobile/mfw/client/images/hlayout.png"))); // NOI18N
        HLayoutButton.setText("HLayayout");
        HLayoutButton.setAlignmentY(0.0F);
        HLayoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HLayoutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HLayoutButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        HLayoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HLayoutButtonActionPerformed(evt);
            }
        });

        TextBoxButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazoomobile/mfw/client/images/textbox.png"))); // NOI18N
        TextBoxButton.setText("TextBox");
        TextBoxButton.setAlignmentY(0.0F);
        TextBoxButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextBoxButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextBoxButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        TextBoxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBoxButtonActionPerformed(evt);
            }
        });

        CheckButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazoomobile/mfw/client/images/checkbox.png"))); // NOI18N
        CheckButton.setText("CheckBox");
        CheckButton.setAlignmentX(1.0F);
        CheckButton.setAlignmentY(0.0F);
        CheckButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CheckButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CheckButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonActionPerformed(evt);
            }
        });

        EditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazoomobile/mfw/client/images/edit.png"))); // NOI18N
        EditButton.setText("Edit");
        EditButton.setAlignmentY(0.0F);
        EditButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EditButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        VLayoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazoomobile/mfw/client/images/vlayout.png"))); // NOI18N
        VLayoutButton.setText("VLayayout");
        VLayoutButton.setAlignmentY(0.0F);
        VLayoutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VLayoutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VLayoutButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        VLayoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VLayoutButtonActionPerformed(evt);
            }
        });

        LabelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazoomobile/mfw/client/images/label.png"))); // NOI18N
        LabelButton.setText("Label");
        LabelButton.setAlignmentY(0.0F);
        LabelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LabelButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        LabelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelButtonActionPerformed(evt);
            }
        });

        TableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazoomobile/mfw/client/images/table.png"))); // NOI18N
        TableButton.setText("Table");
        TableButton.setAlignmentY(0.0F);
        TableButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TableButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TableButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        TableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckButton, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(ComboButton, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(TextBoxButton, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(VLayoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(LabelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(HLayoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(EditButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(ListButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(ButtonButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextBoxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VLayoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HLayoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jScrollPane3.setViewportView(jList3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Properties", "Values"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                inputChanged(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                onKeyPress(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 230, 480));

        main_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        main_panel.setAlignmentY(1.0F);
        main_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                main_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                main_panelMouseExited(evt);
            }
        });
        main_panel.setLayout(new javax.swing.BoxLayout(main_panel, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane2.setViewportView(main_panel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 470));

        jMenu1.setText("APP");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Close");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Screen");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("New");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Save");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addPropertiesToContainer(List<ControlProperty> properties) {
//        jList1.setModel(new DefaultListModel());
//        jList2.setModel(new DefaultListModel());
        //jTable1.setModel(new DefaultTableModel());

//        Control f = new Control();
//        f.setControlName("asfasf");
//
//        ControlDefinition def = new ControlDefinition();
//        def.setValue("asfasfas");
//
//        f.

        String[][] values = new String[properties.size()][2];
        for (int i = 0; i < properties.size(); i++) {
            values[i][0] = properties.get(i).getName();
            values[i][1] = "Value";
        }

        DefaultTableModel dtm = new DefaultTableModel(values, new String[]{"Properties", "Values"}) {

            boolean[] canEdit = new boolean[]{
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        jTable1.setModel(dtm);
    }

    private void ButtonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonButtonActionPerformed
        ButtonButton.setBorder(null);
        activeComponent = "Button";
    }//GEN-LAST:event_ButtonButtonActionPerformed

    public void OnComponentDelete(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            JPanel owner = (JPanel) evt.getComponent().getParent();
            owner.remove(evt.getComponent());
            owner.revalidate();
            owner.repaint();
        }
    }

    private void ListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListButtonActionPerformed
        LabelButton.setBorder(null);
        activeComponent = "ListBox";
    }//GEN-LAST:event_ListButtonActionPerformed

    private void LabelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelButtonActionPerformed
//        if(activeComponent=="ListBox"){
//        LabelButton.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
//        activeComponent = "";
//       }
//       else {
        LabelButton.setBorder(null);
        activeComponent = "Label";
//       }
    }//GEN-LAST:event_LabelButtonActionPerformed

    public void CreateApplication(String model, String name, String description) {
        main_panel.removeAll();
        //Models: 9000, 9500, 9530, 9630, 9700
        if (model.equals("9000")) {
            main_panel.setSize(480, 320);
        } else {
            main_panel.setSize(480, 360);
        }
        main_panel.repaint();
        application = new Application();
        application.setName(name);
        application.setDescription(description);
    }

    public void CreateScreen(String name, String description, boolean isDefaultScreen) {
        actualScreen = new Screen();
        actualScreen.setDescription(description);
        actualScreen.setName(name);
        actualScreen.setDefaultScreen(isDefaultScreen);
    }

    private void ComboButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboButtonActionPerformed
        ComboButton.setBorder(null);
        activeComponent = "ComboBox";
    }//GEN-LAST:event_ComboButtonActionPerformed

    private void CheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButtonActionPerformed
        CheckButton.setBorder(null);
        activeComponent = "CheckBox";
    }//GEN-LAST:event_CheckButtonActionPerformed

    private void TextBoxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBoxButtonActionPerformed
        TextBoxButton.setBorder(null);
        activeComponent = "TextBox";
    }//GEN-LAST:event_TextBoxButtonActionPerformed

    private void HLayoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HLayoutButtonActionPerformed
        HLayoutButton.setBorder(null);
        activeComponent = "HLayout";
    }//GEN-LAST:event_HLayoutButtonActionPerformed

    private void TableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableButtonActionPerformed
        TableButton.setBorder(null);
        activeComponent = "Table";
    }//GEN-LAST:event_TableButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        EditButton.setBorder(null);
        activeComponent = "TextField";
    }//GEN-LAST:event_EditButtonActionPerformed

    private void VLayoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VLayoutButtonActionPerformed
        VLayoutButton.setBorder(null);
        activeComponent = "VLayout";
    }//GEN-LAST:event_VLayoutButtonActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_jPanel4MouseClicked

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
//       CrearApp pantalla = new CrearApp(this);
//       pantalla.setVisible(true);
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

//        Pantalla p = new Pantalla(LayoutType.VERTICAL);
//        App.AdicionarPantalla(p);
        ;
//	  actualScreen.setDatasources(dss);
//	  actualScreen.setControls(controls);
        //List<Screen> screens = new ArrayList<Screen>();
        //screens.add(actualScreen);
        CreateScreen pantalla = new CreateScreen(this);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
//        App = new Aplicacion();
//        pantallaActual=0;
//        componenteActual=0;
//	application.setUsers(users);
//	application.setScreens(screens);
        CreateApplication pantalla = new CreateApplication(this);
        pantalla.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void main_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_panelMouseEntered
        onJPanelMouseEntered(evt);
    }//GEN-LAST:event_main_panelMouseEntered

    private void main_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_panelMouseExited
        onJPanelMouseExited(evt);
    }//GEN-LAST:event_main_panelMouseExited

    private void onKeyPress(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onKeyPress
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            JOptionPane.showMessageDialog(this, "onKeyPress");
        }
    }//GEN-LAST:event_onKeyPress

    private void inputChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputChanged
        JOptionPane.showMessageDialog(this, "inputChanged");
    }//GEN-LAST:event_inputChanged

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void main_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_panelMouseClicked
        AddComponentToActivePanel();
    }//GEN-LAST:event_main_panelMouseClicked

    private void AddComponentToActivePanel() {
        if (activeComponent.equals("Label")) {
            MyOwnLabel label = new MyOwnLabel("Label1", this, "2");
            label.setAlignmentX(Component.CENTER_ALIGNMENT);
            activePanel.add(label);
            activePanel.add(Box.createRigidArea(new Dimension(5, 5)));
            activePanel.getLayout().layoutContainer(activePanel);
            activePanel.repaint();
        } else if (activeComponent.equals("Button")) {
            MyOwnButton button = new MyOwnButton("Button", this, "2");
            button.setAlignmentX(Component.CENTER_ALIGNMENT);
            activePanel.add(button);
            activePanel.add(Box.createRigidArea(new Dimension(5, 5)));
            activePanel.getLayout().layoutContainer(activePanel);
            activePanel.repaint();
        } else if (activeComponent.equals("ComboBox")) {
            MyOwnComboBox comboBox = new MyOwnComboBox(this, "2");
            comboBox.setAlignmentX(Component.CENTER_ALIGNMENT);
            activePanel.add(comboBox);
            activePanel.add(Box.createRigidArea(new Dimension(5, 5)));
            activePanel.getLayout().layoutContainer(activePanel);
            activePanel.repaint();
        } else if (activeComponent.equals("CheckBox")) {
            MyOwnCheckBox checkBox = new MyOwnCheckBox("checkBox1", this, "2");
            checkBox.setAlignmentX(Component.CENTER_ALIGNMENT);
            activePanel.add(checkBox);
            activePanel.add(Box.createRigidArea(new Dimension(5, 5)));
            activePanel.getLayout().layoutContainer(activePanel);
            activePanel.repaint();
        } else if (activeComponent.equals("ListBox")) {
            MyOwnListBox listBox = new MyOwnListBox(this, "2");
            listBox.setAlignmentX(Component.CENTER_ALIGNMENT);
            activePanel.add(listBox);
            activePanel.add(Box.createRigidArea(new Dimension(5, 5)));
            activePanel.getLayout().layoutContainer(activePanel);
            activePanel.repaint();
        } else if (activeComponent.equals("TextField")) {
            MyOwnTextField textField = new MyOwnTextField(this, "2");
            textField.setAlignmentX(Component.CENTER_ALIGNMENT);
            activePanel.add(textField);
            activePanel.add(Box.createRigidArea(new Dimension(5, 5)));
            activePanel.getLayout().layoutContainer(activePanel);
            activePanel.repaint();
        } else if (activeComponent.equals("TextBox")) {
            MyOwnTextBox textBox = new MyOwnTextBox(this, "2");
            textBox.setAlignmentX(Component.CENTER_ALIGNMENT);
            activePanel.add(textBox);
            activePanel.add(Box.createRigidArea(new Dimension(5, 5)));
            activePanel.getLayout().layoutContainer(activePanel);
            activePanel.repaint();
        } else if (activeComponent.equals("Table")) {
            MyOwnTable table = new MyOwnTable(this, "2");
            table.setAlignmentX(Component.CENTER_ALIGNMENT);
            activePanel.add(table);
            activePanel.add(Box.createRigidArea(new Dimension(5, 5)));
            activePanel.getLayout().layoutContainer(activePanel);
            activePanel.repaint();
        } else if (activeComponent.equals("HLayout")) {
            // Horizontal Layout
            JPanel layout = new JPanel();
            layout.setBorder(BorderFactory.createLineBorder(Color.RED));
            layout.addMouseListener(new java.awt.event.MouseAdapter() {

                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    onJPanelMouseEntered(evt);
                }

                public void mouseExited(java.awt.event.MouseEvent evt) {
                    onJPanelMouseExited(evt);
                }

                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    AddComponentToActivePanel();
                }
            });
            layout.setLayout(new BoxLayout(layout, BoxLayout.X_AXIS));
            layout.setAlignmentX(Component.CENTER_ALIGNMENT);
            layout.add(Box.createRigidArea(new Dimension(10, 5)));

            layout.revalidate();
            layout.repaint();

            activePanel.add(layout);
            activePanel.add(Box.createRigidArea(new Dimension(5, 5)));
            activePanel.revalidate();
            activePanel.repaint();
        } else if (activeComponent.equals("VLayout")) {
            // Vertical Layout
            JPanel layout = new JPanel();
            layout.setBorder(BorderFactory.createLineBorder(Color.RED));
            layout.addMouseListener(new java.awt.event.MouseAdapter() {

                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    onJPanelMouseEntered(evt);
                }

                public void mouseExited(java.awt.event.MouseEvent evt) {
                    onJPanelMouseExited(evt);
                }

                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    AddComponentToActivePanel();
                }
            });
            layout.setLayout(new BoxLayout(layout, BoxLayout.Y_AXIS));
            layout.setAlignmentX(Component.CENTER_ALIGNMENT);
            layout.add(Box.createRigidArea(new Dimension(5, 10)));

            layout.revalidate();
            layout.repaint();

            activePanel.add(layout);
            activePanel.add(Box.createRigidArea(new Dimension(5, 5)));
            activePanel.revalidate();
            activePanel.repaint();
        }
    }

    public void onJPanelMouseEntered(java.awt.event.MouseEvent evt) {
        ((JPanel) evt.getSource()).setBorder(BorderFactory.createLineBorder(Color.BLUE));
//         main_panel.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        activePanel = (JPanel) evt.getSource();
    }

    public void onJPanelMouseExited(java.awt.event.MouseEvent evt) {
        ((JPanel) evt.getSource()).setBorder(BorderFactory.createEtchedBorder());
//           main_panel.setBorder(BorderFactory.createEtchedBorder());
        activePanel = main_panel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JPrincipal().setVisible(true);

            }
        });
    }

    /**
     * @return the application
     */
    public Application getApplication() {
        return application;
    }

    /**
     * @param application the application to set
     */
    public void setApplication(Application application) {
        this.application = application;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonButton;
    private javax.swing.JButton CheckButton;
    private javax.swing.JButton ComboButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton HLayoutButton;
    private javax.swing.JButton LabelButton;
    private javax.swing.JButton ListButton;
    private javax.swing.JButton TableButton;
    private javax.swing.JButton TextBoxButton;
    private javax.swing.JButton VLayoutButton;
    private javax.swing.JList jList3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel main_panel;
    // End of variables declaration//GEN-END:variables
}
