
package com.gazoomobile.mfw.platform.clientapi;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ApplicationWebService", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApplicationWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.gazoomobile.mfw.platform.clientapi.Application>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllActiveApplications", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetAllActiveApplications")
    @ResponseWrapper(localName = "getAllActiveApplicationsResponse", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetAllActiveApplicationsResponse")
    public List<Application> getAllActiveApplications();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.gazoomobile.mfw.platform.clientapi.Application
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createOrUpdateApplication", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.CreateOrUpdateApplication")
    @ResponseWrapper(localName = "createOrUpdateApplicationResponse", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.CreateOrUpdateApplicationResponse")
    public Application createOrUpdateApplication(
        @WebParam(name = "arg0", targetNamespace = "")
        Application arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.gazoomobile.mfw.platform.clientapi.ApplicationDescriptionDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllActiveApplicationDescriptions", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetAllActiveApplicationDescriptions")
    @ResponseWrapper(localName = "getAllActiveApplicationDescriptionsResponse", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetAllActiveApplicationDescriptionsResponse")
    public List<ApplicationDescriptionDto> getAllActiveApplicationDescriptions();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.gazoomobile.mfw.platform.clientapi.Application
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplicationById", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetApplicationById")
    @ResponseWrapper(localName = "getApplicationByIdResponse", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetApplicationByIdResponse")
    public Application getApplicationById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
