
package com.gazoomobile.mfw.platform.clientapi;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ConnectorWebService", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConnectorWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.gazoomobile.mfw.platform.clientapi.ConnectorType>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllConectorTypes", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetAllConectorTypes")
    @ResponseWrapper(localName = "getAllConectorTypesResponse", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetAllConectorTypesResponse")
    public List<ConnectorType> getAllConectorTypes();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.gazoomobile.mfw.platform.clientapi.ConnectorProperty>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllConnectorProperties", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetAllConnectorProperties")
    @ResponseWrapper(localName = "getAllConnectorPropertiesResponse", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetAllConnectorPropertiesResponse")
    public List<ConnectorProperty> getAllConnectorProperties(
        @WebParam(name = "arg0", targetNamespace = "")
        ConnectorType arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.gazoomobile.mfw.platform.clientapi.ConnectorProperty>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllConnectorPropertiesByName", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetAllConnectorPropertiesByName")
    @ResponseWrapper(localName = "getAllConnectorPropertiesByNameResponse", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetAllConnectorPropertiesByNameResponse")
    public List<ConnectorProperty> getAllConnectorPropertiesByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
