
package com.gazoomobile.mfw.platform.clientapi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ConnectorWebServiceImpl", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", wsdlLocation = "http://localhost:8080/MFW/services/ConnectorService?wsdl")
public class ConnectorWebServiceImpl
    extends Service
{

    private final static URL CONNECTORWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.gazoomobile.mfw.platform.clientapi.ConnectorWebServiceImpl.class.getName());
    private static final QName serviceName;

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.gazoomobile.mfw.platform.clientapi.ConnectorWebServiceImpl.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/MFW/services/ConnectorService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/MFW/services/ConnectorService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONNECTORWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        serviceName = new QName("http://impl.web.platform.mfw.gazoomobile.com/", "ConnectorWebServiceImplService");
    }

    public ConnectorWebServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public ConnectorWebServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, serviceName);
    }

    public ConnectorWebServiceImpl() {
        super(CONNECTORWEBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.web.platform.mfw.gazoomobile.com/", "ConnectorWebServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns ConnectorWebService
     */
    @WebEndpoint(name = "ConnectorWebServiceImplPort")
    public ConnectorWebService getConnectorWebServiceImplPort() {
        return super.getPort(new QName("http://impl.web.platform.mfw.gazoomobile.com/", "ConnectorWebServiceImplPort"), ConnectorWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConnectorWebService
     */
    @WebEndpoint(name = "ConnectorWebServiceImplPort")
    public ConnectorWebService getConnectorWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.web.platform.mfw.gazoomobile.com/", "ConnectorWebServiceImplPort"), ConnectorWebService.class, features);
    }

}
