
package com.gazoomobile.mfw.platform.clientapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "MfwSecutiryError", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/")
public class MfwSecutiryException
    extends Exception
{
	private static final long serialVersionUID = -5111703271668438716L;
	
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MfwSecutiryError faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public MfwSecutiryException(String message, MfwSecutiryError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public MfwSecutiryException(String message, MfwSecutiryError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.gazoomobile.mfw.platform.clientapi.MfwSecutiryError
     */
    public MfwSecutiryError getFaultInfo() {
        return faultInfo;
    }

}
