
package com.gazoomobile.mfw.platform.clientapi;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UserWebService", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWebService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeUser", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.RemoveUser")
    @ResponseWrapper(localName = "removeUserResponse", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.RemoveUserResponse")
    public void removeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createOrUpdateUser", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.CreateOrUpdateUser")
    @ResponseWrapper(localName = "createOrUpdateUserResponse", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.CreateOrUpdateUserResponse")
    public void createOrUpdateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.gazoomobile.mfw.platform.clientapi.User
     * @throws MfwSecutiryException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.LoginResponse")
    public User login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws MfwSecutiryException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.gazoomobile.mfw.platform.clientapi.Application>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUserApplications", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetAllUserApplications")
    @ResponseWrapper(localName = "getAllUserApplicationsResponse", targetNamespace = "http://impl.web.platform.mfw.gazoomobile.com/", className = "com.gazoomobile.mfw.platform.clientapi.GetAllUserApplicationsResponse")
    public List<Application> getAllUserApplications(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
