package com.gazoomobile.mfw.client.view;

import com.gazoomobile.mfw.platform.clientapi.Screen;

public class ScreenView extends javax.swing.JDialog {

    public ScreenView(java.awt.Frame parent, boolean modal, MainView viewOwner) {
        super(parent, modal);
        this.viewOwner = viewOwner;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create_app_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        screenName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionName = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        msg_label = new javax.swing.JLabel();
        mf_name = new javax.swing.JLabel();
        mf_name1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Screen");
        setResizable(false);

        create_app_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Screen"));
        create_app_panel.setPreferredSize(new java.awt.Dimension(264, 310));
        create_app_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name: ");
        create_app_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        screenName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                screenNameKeyPressed(evt);
            }
        });
        create_app_panel.add(screenName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, -1));

        jLabel2.setText("Description:");
        create_app_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        descriptionName.setColumns(20);
        descriptionName.setFont(new java.awt.Font("Arial", 0, 11));
        descriptionName.setRows(5);
        descriptionName.setPreferredSize(new java.awt.Dimension(162, 95));
        descriptionName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descriptionNameKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(descriptionName);

        create_app_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 340, 110));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        create_app_panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jButton2.setText("Accept");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        create_app_panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));
        create_app_panel.add(msg_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        mf_name.setFont(new java.awt.Font("Arial", 0, 11));
        mf_name.setText("[*]");
        create_app_panel.add(mf_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        mf_name1.setFont(new java.awt.Font("Arial", 0, 11));
        mf_name1.setText("[*] Mandatory Field");
        create_app_panel.add(mf_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jCheckBox1.setText("Default Screen");
        create_app_panel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(create_app_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(create_app_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void screenNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_screenNameKeyPressed
        mf_name.setForeground(new java.awt.Color(0, 0, 0));
}//GEN-LAST:event_screenNameKeyPressed

    private void descriptionNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptionNameKeyPressed
}//GEN-LAST:event_descriptionNameKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        screenName.setText("");
        descriptionName.setText("");
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
}//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!screenName.getText().equals("")) {
            Screen screen = new Screen();
            screen.setName(screenName.getText());
            screen.setDescription(descriptionName.getText());
            screen.setDefaultScreen(jCheckBox1.isSelected());
            viewOwner.addScreen(screen);
            setVisible(false);
        }
        mf_name.setForeground(new java.awt.Color(204, 0, 0));
    }//GEN-LAST:event_jButton2ActionPerformed

        public static void main(String args[]) {
            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                    ScreenView dialog = new ScreenView(new javax.swing.JFrame(), true, new MainView());
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                }
            });
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel create_app_panel;
    private javax.swing.JTextArea descriptionName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mf_name;
    private javax.swing.JLabel mf_name1;
    private javax.swing.JLabel msg_label;
    private javax.swing.JTextField screenName;
    // End of variables declaration//GEN-END:variables
    private MainView viewOwner;
}
