/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ApplicationView.java
 *
 * Created on 31-may-2010, 23:16:12
 */

package com.gazoomobile.mfw.client.view;

import com.gazoomobile.mfw.platform.client.Application;

public class ApplicationView extends javax.swing.JDialog {

    /** Creates new form ApplicationView */
    public ApplicationView(java.awt.Frame parent, boolean modal, MainView owner) {
        super(parent, modal);
        this.owner = owner;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create_app_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        app_name_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        app_description_field = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        msg_label = new javax.swing.JLabel();
        blackberry_model_combo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Application");

        create_app_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Application"));
        create_app_panel.setPreferredSize(new java.awt.Dimension(264, 310));
        create_app_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name: ");
        create_app_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        app_name_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                app_name_fieldKeyPressed(evt);
            }
        });
        create_app_panel.add(app_name_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, -1));

        jLabel2.setText("Description:");
        create_app_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        app_description_field.setColumns(20);
        app_description_field.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        app_description_field.setRows(5);
        app_description_field.setPreferredSize(new java.awt.Dimension(162, 95));
        app_description_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                app_description_fieldKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(app_description_field);

        create_app_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 380, 110));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        create_app_panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 240, -1, -1));

        jButton2.setText("Accept");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        create_app_panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));
        create_app_panel.add(msg_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        blackberry_model_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9000", "9500", "9530", "9630", "9700" }));
        create_app_panel.add(blackberry_model_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 65, 110, -1));

        jLabel3.setText("Blackberry Models:");
        create_app_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(create_app_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(create_app_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       if(!app_name_field.getText().equals("")&& !app_description_field.getText().equals("")){
            Application application = new Application();
            application.setName(app_name_field.getText());
            application.setDescription(app_description_field.getText());
            System.out.println("application" + application);
            owner.addApplication(application);
            app_name_field.setText("");
            app_description_field.setText("");
       }
       else{
            msg_label.setText("You should complete all fields");
       }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void app_name_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_app_name_fieldKeyPressed
        if(!msg_label.getText().equals(""))
            msg_label.setText("");        
    }//GEN-LAST:event_app_name_fieldKeyPressed

    private void app_description_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_app_description_fieldKeyPressed
        if(!msg_label.getText().equals(""))
            msg_label.setText("");
    }//GEN-LAST:event_app_description_fieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea app_description_field;
    private javax.swing.JTextField app_name_field;
    private javax.swing.JComboBox blackberry_model_combo;
    private javax.swing.JPanel create_app_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msg_label;
    // End of variables declaration//GEN-END:variables
    private MainView owner;
}
