/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataSourceView.java
 * Created on 05-jun-2010, 8:11:49
 */

package com.gazoomobile.mfw.client.view;
import com.gazoomobile.mfw.client.database.Database;
import com.gazoomobile.mfw.connector.ConnectorException;
import com.gazoomobile.mfw.client.interfaces.ISqlCommand;
import com.gazoomobile.mfw.connector.db.Table;
import com.gazoomobile.mfw.connector.db.oracle.OracleConnector;
import com.gazoomobile.mfw.platform.client.Datasource;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DataSourceView extends javax.swing.JFrame implements ISqlCommand{

    /** Creates new form DataSourceView */
    public DataSourceView(MainView owner) {
        this.owner = owner;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        portField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        databaseField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nameDSField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        jLabel5.setText("jLabel5");

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create DataSource");
        setMinimumSize(new java.awt.Dimension(340, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Database"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameField.setText("10.36.19.106");
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 170, -1));

        jLabel1.setText("IP/Name: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 20, -1, -1));

        portField.setText("1521");
        jPanel1.add(portField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 170, -1));

        jLabel2.setText("Port:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        databaseField.setText("db_facultad");
        jPanel1.add(databaseField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 170, -1));

        jLabel8.setText("Database:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 310, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameDSField.setText("Oracle");
        jPanel3.add(nameDSField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 169, -1));

        jLabel7.setText("DataSource Name:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 310, 60));

        jButton1.setText("Connect");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jButton2.setText("Cancel");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Password: ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 60, -1, -1));

        userNameField.setText("patrulla");
        jPanel4.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 170, -1));

        jLabel3.setText("User: ");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 20, -1, -1));

        passwordField.setText("desarrollo");
        jPanel4.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 170, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 310, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String dsName = nameDSField.getText();
        String dsIPName = nameField.getText();
        String dsPort = portField.getText();
        String dsUser = userNameField.getText();
        String dsPassword = new String(passwordField.getPassword());
        String dsDatabase = databaseField.getText();

        Properties conf = new Properties();
        conf.setProperty(OracleConnector.SID_PROP_KEY, "UPPDB");
        conf.setProperty(OracleConnector.PORT_PROP_KEY, dsPort);
        conf.setProperty(OracleConnector.SERVER_PROP_KEY, dsIPName);
        conf.setProperty(OracleConnector.USER_PROP_KEY, dsUser);
        conf.setProperty(OracleConnector.PASS_PROP_KEY, dsPassword);
        OracleConnector connector = new OracleConnector(conf);
        
        Database database = null;
        try {
            List<Table> tables = connector.allTablesByOwner("PATRULLA");
            database = new Database(dsDatabase, tables);
        }
        catch (ConnectorException ex) {
            Logger.getLogger(DataSourceView.class.getName()).log(Level.SEVERE, null, ex);
        }
        ds = new Datasource();
        ds.setName(dsName);
        SQLCommandView commandView = new SQLCommandView(this, ds, database);
        commandView.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setSQLCommand(String command) {
        owner.addChildSelectedNode(ds.getName());
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataSourceView(new MainView()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField databaseField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField nameDSField;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField portField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
    private Datasource ds;
    private MainView owner;
}
